### ISSUE TITLE
Multiple keyboard shortcuts

### ISSUE THREAD

**Issue by jasonesiegel** [lucwastiaux/anki-quick-edit#1]
Hi, thanks for the Quick Field Focus add-on. What is the syntax to add multiple keyboard shortcuts (for multiple fields)? Not sure how to concatenate in the config

**Comment by luc-vocab** [comment]
Believe it or not, I had a bug which prevented multiple shortcuts to be configured ! I fixed it just now and published an update to the addon (please have anki check for updates on Quick Field Focus if it didn't prompt you).

Here's how you configure multiple fields:

    {
        "focus_field_shortcuts": [
            {
                "field": "Example",
                "note_type": "Chinese-Words",
                "shortcut": "Ctrl+H"
            },
            {
                "field": "Romanization",
                "note_type": "Chinese-Words",
                "shortcut": "Ctrl+G"
            }
        ]
    }

**Comment by luc-vocab** [comment]
I added these examples on the addon page: https://ankiweb.net/shared/info/1199312228
if this answers your question satisfactorily, please leave a review on the addon page !

**Comment by jasonesiegel** [comment]
haha thanks!

**Comment by jasonesiegel** [comment]
Thanks. However, it appears that I'm still having some trouble getting this to work. I'm on Mac.

{
    "focus_field_shortcuts": [
        {
            "field": "e1",
            "note_type": "Translation",
            "shortcut": "Cmd+1"
        },
        {
            "field": "e2",
            "note_type": "Translation",
            "shortcut": "Cmd+2"
        },
        {
            "field": "e3",
            "note_type": "Translation",
            "shortcut": "Cmd+3"
        },
        {
            "field": "k2",
            "note_type": "Translation",
            "shortcut": "Alt+Cmd+1"
        },
        {
            "field": "k2",
            "note_type": "Translation",
            "shortcut": "Alt+Cmd+1"
        },
        {
            "field": "k2",
            "note_type": "Translation",
            "shortcut": "Alt+Cmd+1"
        }
    ]
}

**Comment by luc-vocab** [comment]
That looks correct to me, what is happening?

**Comment by luc-vocab** [comment]
Just to confirm, you updated to the latest version of the add-on? Anki should have prompted you to update. Also, when making a config change, you have to restart anki.

**Comment by jasonesiegel** [comment]
I have. Just can't seem to get the shortcuts to work.

**Comment by luc-vocab** [comment]
Do you know how to start Anki from the command line , on the terminal ? It may print valuable messages which may help us resolve this problem. Please try this first, and I will prepare a version of the addon with enhanced logging to print even more information.

**Comment by luc-vocab** [comment]
Let me know whether you got around to starting Anki from the command line. I expect it would show some interesting information, such as potential keyboard shortcut conflicts.

**Comment by jasonesiegel** [comment]
Haven’t tried yet, but just found this comment in a different add-on:

"Aside: if it helps anyone else, I've finally figured out how to get hotkeys working on a mac.
You need to insert the symbol version of the keys, rather than the text version.
So instead of typing Shift+Command+E, you need to type ⇧⌘E. This drove me crazy for a wee while!"

**Comment by luc-vocab** [comment]
OK it's becoming clearer now. Anki's source code explains this clearly: you have to define your shortcuts as "Ctrl+1", then you'll be able to use Command+1 to activate them on a mac. Could you try this ?

**Comment by luc-vocab** [comment]
Let me know whether this works !

**Comment by jasonesiegel** [comment]
Hi, thanks for the note. It’s been a very busy week, but I have this on my todo list and will get back to you

**Comment by jasonesiegel** [comment]
No luck. Here's what I tried. Some of this combos had text outputs though so they may already be taken. Not sure how to start from Terminal, sorry.

```
{
    "focus_field_shortcuts": [
        {
            "field": "e1",
            "note_type": "Translation",
            "shortcut": "Shift+Ctrl+1"
        },
        {
            "field": "e2",
            "note_type": "Translation",
            "shortcut": "Ctrl+2"
        },
        {
            "field": "e3",
            "note_type": "Translation",
            "shortcut": "Ctrl+3"
        },
        {
            "field": "k2",
            "note_type": "Translation",
            "shortcut": "Alt+Ctrl+1"
        },
        {
            "field": "k2",
            "note_type": "Translation",
            "shortcut": "Alt+Ctrl+1"
        },
        {
            "field": "k2",
            "note_type": "Translation",
            "shortcut": "Alt+Ctrl+1"
        }
    ]
}
```
